version: '3'

volumes:
  static:
  database:

services:
  django_study:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: django_study
    container_name: django_study
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: django_study
    container_name: django_study
    volumes:
      - static:/apps/django_study/static
    ports:
      - "80:80"
      - "443:443"